version: '3.7'

services:
  db:
    # docker run --name mongodb_exam mongo:latest
    image: mongo:latest
    container_name: mongodb_exam
    
  back:
    # "abc" est le nom de l'image, en vériter docker compose en génére un automatiquement via son hash
    # docker build -f Dockerfile -t abc .
    # docker run --name back_exam -p 8000:8000 abc
    # pour les ports, le premier est le port de la machine et le second est le port du container
    # ex. machine:container
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_exam
    ports:
      - "8000:8000"
    depends_on:
      - db

# Pour lancer : docker compose up --build
# Pour eteindre : docker compose down